apiVersion: v1
kind: Service
metadata:
  name: legions-application
spec:
  selector:
    app: legions-app
  ports:
    - name: http
      port: 8088
      nodePort: 30888
      protocol: TCP
      targetPort: 80
  type: NodePort
